# LanceDB fundamentals

In [1]:
import lancedb 
from constants import KNOWLEDGE_BASE_PATH

vector_db = lancedb.connect(KNOWLEDGE_BASE_PATH)
vector_db

LanceDBConnection(uri='c:\\Users\\norel\\Project\\LLMOps_Nore_Lindkvist_Mlops25\\09_lancedb\\knowledge_base')

In [2]:
import json 

with open("data/animals_text_embeddings.json") as file:
    data = json.load(file)

In [6]:
vector_db.create_table("animals_text", exist_ok=True, data=data)
vector_db["animals_text"]

LanceTable(name='animals_text', version=1, _conn=LanceDBConnection(uri='c:\\Users\\norel\\Project\\LLMOps_Nore_Lindkvist_Mlops25\\09_lancedb\\knowledge_base'))

In [7]:
vector_db["animals_text"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]

In [8]:
vector_db["animals_text"].head()

pyarrow.Table
text: string
vector: fixed_size_list<item: float>[3]
  child 0, item: float
----
text: [["A small brown dog running.","A cat resting quietly on a sofa.","A large gray elephant drinking water.","A fast cheetah sprinting across the savannah.","A colorful parrot perched on a branch."]]
vector: [[[0.12,0.85,0.33],[0.4,0.91,0.1],[0.88,0.22,0.55],[0.95,0.12,0.72],[0.25,0.66,0.81]]]

## Add more data

In [10]:
more_data= more_data = [
    {"text": "A panda eating bamboo peacefully.", "vector": [0.51, 0.37, 0.82]},
    {"text": "A lion roaring loudly on a rock.", "vector": [0.93, 0.18, 0.41]},
]

vector_db["animals_text"].add(more_data)

AddResult(version=2)

In [11]:
vector_db["animals_text"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

# Create empty table

In [13]:
from lancedb.pydantic import LanceModel

class Article(LanceModel):
    title: str
    content: str

vector_db.create_table("aricles", schema= Article, exist_ok=True)

LanceTable(name='aricles', version=1, _conn=LanceDBConnection(uri='c:\\Users\\norel\\Project\\LLMOps_Nore_Lindkvist_Mlops25\\09_lancedb\\knowledge_base'))

In [ ]:
vector_db.list_tables()

ListTablesResponse(tables=['animals_text', 'aricles'], page_token=None)

In [ ]:
articles_data = [
    {
        "title": "World War 2",
        "content": "Andra världskriget var en väpnad konflikt som pågick från hösten 1939 till hösten 1945 och som involverade de flesta av världens nationer, inklusive alla stormakter.",
    },
    {
        "title": "Fiskar",
        "content": """Fiskar (Pisces) är en grupp vattenlevande ryggradsdjur med fenor, som indelas i benfiskar, broskfiskar och käklösa fiskar. De flesta arter andas med gälar och är växelvarma. Undantaget är lungfiskar. Eftersom landryggradsdjuren släktskapsmässigt är en typ av kvastfeniga fiskar men inte klassificeras som fiskar är begreppet "fiskar" parafyletiskt. Vetenskapen om fiskar kallas iktyologi.""",
    },
    {
        "title": "Krabba",
        "content": """Krabbor (Brachyura) är en delordning av vattenlevande kräftdjur. Vissa arter fiskas som mat, ofta ansedda som delikatesser. Krabbor har tio ben varav det första paret bär gripklor.""",
    },
]

## TODO: add data to articles table